### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by MingHuiLiu** [34673/ZEQ2-Lite#6]
Building ZEQ2-Lite in Build/Release-linux-x86_64:
PLATFORM: linux
ARCH: x86_64
VERSION: 1.36
COMPILE_PLATFORM: linux
COMPILE_ARCH: x86_64
CC: cc

make[2]: Entering directory '/data/projects/ZEQ2-Lite-1'
make[2]: *** No rule to make target 'Build/Release-linux-x86_64/ded/null_client.o', needed by 'Build/Release-linux-x86_64/DedicatedServer.x86_64'。 停止。
make[2]: Leaving directory '/data/projects/ZEQ2-Lite-1'
Makefile:1182: recipe for target 'targets' failed
make[1]: *** [targets] Error 2
make[1]: Leaving directory '/data/projects/ZEQ2-Lite-1'
Makefile:1133: recipe for target 'release' failed

**Comment by MingHuiLiu** [comment]
@34673

**Comment by 34673** [comment]
Hello. There was an issue with cases when I sent changes to the Zlib and Null directories in the engine. The Makefile is now looking for "Null" and "Zlib", not "null" and "zlib". I don't know how to fix that from Github itself, so I might have to reupload those folders. For the time being, just rename them accordingly to the Makefile. The coding standards I'm basing this on normally use Title Case for folders, but since I fear it would be causing problems with various tools, I am for now sticking with PascalCase.
